[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
package-dir = {'' = 'src'}

[project]
name = 'raspberry-py'
version = '0.5.0'
description = 'A Python/REST interface for GPIO circuits running on the Raspberry Pi'
authors = [
    {name = 'Matthew Gerber', email = 'gerber.matthew@gmail.com'}
]
readme = 'README.md'
requires-python = '~=3.12'
dependencies = [
    'numpy~=1.26',
    'RPi.GPIO~=0.7',
    'smbus2~=0.4',
    'Flask~=3.0',
    'Flask-Cors~=4.0',
    'opencv-python~=4.8',
    'rpi-ws281x~=5.0'
]

[project.optional-dependencies]
dev = [
    'bump2version~=1.0'
]

[project.urls]
Repository = 'https://github.com/MatthewGerber/raspberry-py'
Homepage = 'https://matthewgerber.github.io/raspberry-py'

[project.scripts]
write_component_files = 'raspberry_py.rest.application:write_component_files_cli'
