theme: jekyll-theme-cayman

include:
 - "**/*.md"

plugins:
  - jekyll-sitemap

title: "raspberry-py"
description: "A Python/REST interface for GPIO circuits running on the Raspberry Pi"
url: "https://matthewgerber.github.io/raspberry-py"
